packages:
  - packages/**/*

catalog:
  '@antfu/eslint-config': 6.0.0
  '@sentry/browser': 9.28.0
  '@sveltejs/kit': 2.47.1
  '@sveltejs/vite-plugin-svelte': 6.2.1
  '@types/node': 24.8.1
  eslint: 9.37.0
  eslint-plugin-svelte: 3.12.4
  fcm-cloudflare-workers: 2.0.1
  firebase: 11.9.0
  jiti: 2.6.1
  sass-embedded: 1.89.1
  svelte: 5.40.2
  svelte-check: 4.3.3
  svelte-eslint-parser: 1.3.3
  typescript: 5.9.3
  vite: 7.1.10
  vitest: 3.2.4
