packages:
  - packages/**/*
catalog:
  "@antfu/eslint-config": 6.0.0
  "@sentry/browser": 9.28.0
  "@sveltejs/kit": 2.21.2
  "@sveltejs/vite-plugin-svelte": 5.1.0
  "@types/node": 24.8.1
  eslint: 9.37.0
  eslint-plugin-svelte: 3.12.4
  fcm-cloudflare-workers: 2.0.1
  firebase: 11.9.0
  jiti: 2.6.1
  sass-embedded: 1.89.1
  svelte: 5.33.17
  svelte-check: 4.2.1
  svelte-eslint-parser: 1.3.3
  typescript: 5.9.3
  vite: 6.3.5
  vitest: 3.2.2
